//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarTrekApi
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://stapi.co/api/v1/soap/series", ConfigurationName="StarTrekAPI.SeriesPortType")]
    public interface SeriesPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stapi.co/api/v1/soap/series/SeriesPortType/getSeriesBaseRequest", ReplyAction="http://stapi.co/api/v1/soap/series/SeriesPortType/getSeriesBaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApiRequest))]
        System.Threading.Tasks.Task<StarTrekApi.getSeriesBaseResponse> getSeriesBaseAsync(StarTrekApi.getSeriesBaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://stapi.co/api/v1/soap/series/SeriesPortType/getSeriesFullRequest", ReplyAction="http://stapi.co/api/v1/soap/series/SeriesPortType/getSeriesFullResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ApiRequest))]
        System.Threading.Tasks.Task<StarTrekApi.getSeriesFullResponse> getSeriesFullAsync(StarTrekApi.getSeriesFullRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesBaseRequest : Request
    {
        
        private string titleField;
        
        private string abbreviationField;
        
        private IntegerRange productionStartYearField;
        
        private IntegerRange productionEndYearField;
        
        private DateRange originalRunStartDateField;
        
        private DateRange originalRunEndDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IntegerRange productionStartYear
        {
            get
            {
                return this.productionStartYearField;
            }
            set
            {
                this.productionStartYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public IntegerRange productionEndYear
        {
            get
            {
                return this.productionEndYearField;
            }
            set
            {
                this.productionEndYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public DateRange originalRunStartDate
        {
            get
            {
                return this.originalRunStartDateField;
            }
            set
            {
                this.originalRunStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public DateRange originalRunEndDate
        {
            get
            {
                return this.originalRunEndDateField;
            }
            set
            {
                this.originalRunEndDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class IntegerRange
    {
        
        private int fromField;
        
        private bool fromFieldSpecified;
        
        private int toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified
        {
            get
            {
                return this.fromFieldSpecified;
            }
            set
            {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified
        {
            get
            {
                return this.toFieldSpecified;
            }
            set
            {
                this.toFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/season")]
    public partial class SeasonBase
    {
        
        private string uidField;
        
        private string titleField;
        
        private SeriesHeader seriesField;
        
        private int seasonNumberField;
        
        private int numberOfEpisodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SeriesHeader series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int seasonNumber
        {
            get
            {
                return this.seasonNumberField;
            }
            set
            {
                this.seasonNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int numberOfEpisodes
        {
            get
            {
                return this.numberOfEpisodesField;
            }
            set
            {
                this.numberOfEpisodesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesHeader
    {
        
        private string uidField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/season")]
    public partial class SeasonHeader
    {
        
        private string uidField;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/episode")]
    public partial class EpisodeBase
    {
        
        private string uidField;
        
        private string titleField;
        
        private string titleGermanField;
        
        private string titleItalianField;
        
        private string titleJapaneseField;
        
        private SeriesHeader seriesField;
        
        private SeasonHeader seasonField;
        
        private int seasonNumberField;
        
        private int episodeNumberField;
        
        private string productionSerialNumberField;
        
        private bool featureLengthField;
        
        private float stardateFromField;
        
        private bool stardateFromFieldSpecified;
        
        private float stardateToField;
        
        private bool stardateToFieldSpecified;
        
        private string yearFromField;
        
        private string yearToField;
        
        private System.DateTime usAirDateField;
        
        private bool usAirDateFieldSpecified;
        
        private System.DateTime finalScriptDateField;
        
        private bool finalScriptDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string titleGerman
        {
            get
            {
                return this.titleGermanField;
            }
            set
            {
                this.titleGermanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string titleItalian
        {
            get
            {
                return this.titleItalianField;
            }
            set
            {
                this.titleItalianField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string titleJapanese
        {
            get
            {
                return this.titleJapaneseField;
            }
            set
            {
                this.titleJapaneseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SeriesHeader series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public SeasonHeader season
        {
            get
            {
                return this.seasonField;
            }
            set
            {
                this.seasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int seasonNumber
        {
            get
            {
                return this.seasonNumberField;
            }
            set
            {
                this.seasonNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int episodeNumber
        {
            get
            {
                return this.episodeNumberField;
            }
            set
            {
                this.episodeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string productionSerialNumber
        {
            get
            {
                return this.productionSerialNumberField;
            }
            set
            {
                this.productionSerialNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool featureLength
        {
            get
            {
                return this.featureLengthField;
            }
            set
            {
                this.featureLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public float stardateFrom
        {
            get
            {
                return this.stardateFromField;
            }
            set
            {
                this.stardateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stardateFromSpecified
        {
            get
            {
                return this.stardateFromFieldSpecified;
            }
            set
            {
                this.stardateFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public float stardateTo
        {
            get
            {
                return this.stardateToField;
            }
            set
            {
                this.stardateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stardateToSpecified
        {
            get
            {
                return this.stardateToFieldSpecified;
            }
            set
            {
                this.stardateToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=13)]
        public string yearFrom
        {
            get
            {
                return this.yearFromField;
            }
            set
            {
                this.yearFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
        public string yearTo
        {
            get
            {
                return this.yearToField;
            }
            set
            {
                this.yearToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=15)]
        public System.DateTime usAirDate
        {
            get
            {
                return this.usAirDateField;
            }
            set
            {
                this.usAirDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usAirDateSpecified
        {
            get
            {
                return this.usAirDateFieldSpecified;
            }
            set
            {
                this.usAirDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=16)]
        public System.DateTime finalScriptDate
        {
            get
            {
                return this.finalScriptDateField;
            }
            set
            {
                this.finalScriptDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finalScriptDateSpecified
        {
            get
            {
                return this.finalScriptDateFieldSpecified;
            }
            set
            {
                this.finalScriptDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/company")]
    public partial class CompanyBase
    {
        
        private string uidField;
        
        private string nameField;
        
        private bool broadcasterField;
        
        private bool collectibleCompanyField;
        
        private bool conglomerateField;
        
        private bool digitalVisualEffectsCompanyField;
        
        private bool distributorField;
        
        private bool gameCompanyField;
        
        private bool filmEquipmentCompanyField;
        
        private bool makeUpEffectsStudioField;
        
        private bool mattePaintingCompanyField;
        
        private bool modelAndMiniatureEffectsCompanyField;
        
        private bool postProductionCompanyField;
        
        private bool productionCompanyField;
        
        private bool propCompanyField;
        
        private bool recordLabelField;
        
        private bool specialEffectsCompanyField;
        
        private bool tvAndFilmProductionCompanyField;
        
        private bool videoGameCompanyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool broadcaster
        {
            get
            {
                return this.broadcasterField;
            }
            set
            {
                this.broadcasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool collectibleCompany
        {
            get
            {
                return this.collectibleCompanyField;
            }
            set
            {
                this.collectibleCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool conglomerate
        {
            get
            {
                return this.conglomerateField;
            }
            set
            {
                this.conglomerateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool digitalVisualEffectsCompany
        {
            get
            {
                return this.digitalVisualEffectsCompanyField;
            }
            set
            {
                this.digitalVisualEffectsCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool distributor
        {
            get
            {
                return this.distributorField;
            }
            set
            {
                this.distributorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool gameCompany
        {
            get
            {
                return this.gameCompanyField;
            }
            set
            {
                this.gameCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool filmEquipmentCompany
        {
            get
            {
                return this.filmEquipmentCompanyField;
            }
            set
            {
                this.filmEquipmentCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool makeUpEffectsStudio
        {
            get
            {
                return this.makeUpEffectsStudioField;
            }
            set
            {
                this.makeUpEffectsStudioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool mattePaintingCompany
        {
            get
            {
                return this.mattePaintingCompanyField;
            }
            set
            {
                this.mattePaintingCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool modelAndMiniatureEffectsCompany
        {
            get
            {
                return this.modelAndMiniatureEffectsCompanyField;
            }
            set
            {
                this.modelAndMiniatureEffectsCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool postProductionCompany
        {
            get
            {
                return this.postProductionCompanyField;
            }
            set
            {
                this.postProductionCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool productionCompany
        {
            get
            {
                return this.productionCompanyField;
            }
            set
            {
                this.productionCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool propCompany
        {
            get
            {
                return this.propCompanyField;
            }
            set
            {
                this.propCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool recordLabel
        {
            get
            {
                return this.recordLabelField;
            }
            set
            {
                this.recordLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool specialEffectsCompany
        {
            get
            {
                return this.specialEffectsCompanyField;
            }
            set
            {
                this.specialEffectsCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool tvAndFilmProductionCompany
        {
            get
            {
                return this.tvAndFilmProductionCompanyField;
            }
            set
            {
                this.tvAndFilmProductionCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool videoGameCompany
        {
            get
            {
                return this.videoGameCompanyField;
            }
            set
            {
                this.videoGameCompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesFull
    {
        
        private string uidField;
        
        private string titleField;
        
        private string abbreviationField;
        
        private int productionStartYearField;
        
        private int productionEndYearField;
        
        private System.DateTime originalRunStartDateField;
        
        private System.DateTime originalRunEndDateField;
        
        private int seasonsCountField;
        
        private int episodesCountField;
        
        private int featureLengthEpisodesCountField;
        
        private CompanyBase productionCompanyField;
        
        private CompanyBase originalBroadcasterField;
        
        private EpisodeBase[] episodesField;
        
        private SeasonBase[] seasonsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int productionStartYear
        {
            get
            {
                return this.productionStartYearField;
            }
            set
            {
                this.productionStartYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int productionEndYear
        {
            get
            {
                return this.productionEndYearField;
            }
            set
            {
                this.productionEndYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime originalRunStartDate
        {
            get
            {
                return this.originalRunStartDateField;
            }
            set
            {
                this.originalRunStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime originalRunEndDate
        {
            get
            {
                return this.originalRunEndDateField;
            }
            set
            {
                this.originalRunEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int seasonsCount
        {
            get
            {
                return this.seasonsCountField;
            }
            set
            {
                this.seasonsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int episodesCount
        {
            get
            {
                return this.episodesCountField;
            }
            set
            {
                this.episodesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int featureLengthEpisodesCount
        {
            get
            {
                return this.featureLengthEpisodesCountField;
            }
            set
            {
                this.featureLengthEpisodesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public CompanyBase productionCompany
        {
            get
            {
                return this.productionCompanyField;
            }
            set
            {
                this.productionCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CompanyBase originalBroadcaster
        {
            get
            {
                return this.originalBroadcasterField;
            }
            set
            {
                this.originalBroadcasterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("episodes", Order=12)]
        public EpisodeBase[] episodes
        {
            get
            {
                return this.episodesField;
            }
            set
            {
                this.episodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seasons", Order=13)]
        public SeasonBase[] seasons
        {
            get
            {
                return this.seasonsField;
            }
            set
            {
                this.seasonsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/company")]
    public partial class CompanyHeader
    {
        
        private string nameField;
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesBase
    {
        
        private string uidField;
        
        private string titleField;
        
        private string abbreviationField;
        
        private int productionStartYearField;
        
        private int productionEndYearField;
        
        private System.DateTime originalRunStartDateField;
        
        private System.DateTime originalRunEndDateField;
        
        private int seasonsCountField;
        
        private int episodesCountField;
        
        private int featureLengthEpisodesCountField;
        
        private CompanyHeader productionCompanyField;
        
        private CompanyHeader originalBroadcasterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int productionStartYear
        {
            get
            {
                return this.productionStartYearField;
            }
            set
            {
                this.productionStartYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int productionEndYear
        {
            get
            {
                return this.productionEndYearField;
            }
            set
            {
                this.productionEndYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime originalRunStartDate
        {
            get
            {
                return this.originalRunStartDateField;
            }
            set
            {
                this.originalRunStartDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime originalRunEndDate
        {
            get
            {
                return this.originalRunEndDateField;
            }
            set
            {
                this.originalRunEndDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int seasonsCount
        {
            get
            {
                return this.seasonsCountField;
            }
            set
            {
                this.seasonsCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int episodesCount
        {
            get
            {
                return this.episodesCountField;
            }
            set
            {
                this.episodesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int featureLengthEpisodesCount
        {
            get
            {
                return this.featureLengthEpisodesCountField;
            }
            set
            {
                this.featureLengthEpisodesCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public CompanyHeader productionCompany
        {
            get
            {
                return this.productionCompanyField;
            }
            set
            {
                this.productionCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public CompanyHeader originalBroadcaster
        {
            get
            {
                return this.originalBroadcasterField;
            }
            set
            {
                this.originalBroadcasterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class ResponseSortClause
    {
        
        private string nameField;
        
        private ResponseSortDirectionEnum directionField;
        
        private bool directionFieldSpecified;
        
        private int clauseOrderField;
        
        private bool clauseOrderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ResponseSortDirectionEnum direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool directionSpecified
        {
            get
            {
                return this.directionFieldSpecified;
            }
            set
            {
                this.directionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int clauseOrder
        {
            get
            {
                return this.clauseOrderField;
            }
            set
            {
                this.clauseOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clauseOrderSpecified
        {
            get
            {
                return this.clauseOrderFieldSpecified;
            }
            set
            {
                this.clauseOrderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public enum ResponseSortDirectionEnum
    {
        
        /// <remarks/>
        ASC,
        
        /// <remarks/>
        DESC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class ResponsePage
    {
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        private int numberOfElementsField;
        
        private int totalElementsField;
        
        private int totalPagesField;
        
        private bool firstPageField;
        
        private bool lastPageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numberOfElements
        {
            get
            {
                return this.numberOfElementsField;
            }
            set
            {
                this.numberOfElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int totalElements
        {
            get
            {
                return this.totalElementsField;
            }
            set
            {
                this.totalElementsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int totalPages
        {
            get
            {
                return this.totalPagesField;
            }
            set
            {
                this.totalPagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool firstPage
        {
            get
            {
                return this.firstPageField;
            }
            set
            {
                this.firstPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool lastPage
        {
            get
            {
                return this.lastPageField;
            }
            set
            {
                this.lastPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class Response
    {
        
        private ResponsePage pageField;
        
        private ResponseSortClause[] sortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponsePage page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("clauses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ResponseSortClause[] sort
        {
            get
            {
                return this.sortField;
            }
            set
            {
                this.sortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class DateRange
    {
        
        private System.DateTime fromField;
        
        private bool fromFieldSpecified;
        
        private System.DateTime toField;
        
        private bool toFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=0)]
        public System.DateTime from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromSpecified
        {
            get
            {
                return this.fromFieldSpecified;
            }
            set
            {
                this.fromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toSpecified
        {
            get
            {
                return this.toFieldSpecified;
            }
            set
            {
                this.toFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class RequestSortClause
    {
        
        private string nameField;
        
        private RequestSortDirectionEnum directionField;
        
        private bool directionFieldSpecified;
        
        private int clauseOrderField;
        
        private bool clauseOrderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public RequestSortDirectionEnum direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool directionSpecified
        {
            get
            {
                return this.directionFieldSpecified;
            }
            set
            {
                this.directionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int clauseOrder
        {
            get
            {
                return this.clauseOrderField;
            }
            set
            {
                this.clauseOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clauseOrderSpecified
        {
            get
            {
                return this.clauseOrderFieldSpecified;
            }
            set
            {
                this.clauseOrderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public enum RequestSortDirectionEnum
    {
        
        /// <remarks/>
        ASC,
        
        /// <remarks/>
        DESC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class RequestPage
    {
        
        private int pageNumberField;
        
        private int pageSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int pageNumber
        {
            get
            {
                return this.pageNumberField;
            }
            set
            {
                this.pageNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class ApiRequest
    {
        
        private string apiKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apiKey
        {
            get
            {
                return this.apiKeyField;
            }
            set
            {
                this.apiKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stapi.co/api/v1/soap/common")]
    public partial class Request : ApiRequest
    {
        
        private RequestPage pageField;
        
        private RequestSortClause[] sortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestPage page
        {
            get
            {
                return this.pageField;
            }
            set
            {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("clauses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public RequestSortClause[] sort
        {
            get
            {
                return this.sortField;
            }
            set
            {
                this.sortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesBaseResponse : Response
    {
        
        private SeriesBase[] seriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("series", Order=0)]
        public SeriesBase[] series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSeriesBaseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stapi.co/api/v1/soap/series", Order=0)]
        public StarTrekApi.SeriesBaseRequest SeriesBaseRequest;
        
        public getSeriesBaseRequest()
        {
        }
        
        public getSeriesBaseRequest(StarTrekApi.SeriesBaseRequest SeriesBaseRequest)
        {
            this.SeriesBaseRequest = SeriesBaseRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSeriesBaseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stapi.co/api/v1/soap/series", Order=0)]
        public StarTrekApi.SeriesBaseResponse SeriesBaseResponse;
        
        public getSeriesBaseResponse()
        {
        }
        
        public getSeriesBaseResponse(StarTrekApi.SeriesBaseResponse SeriesBaseResponse)
        {
            this.SeriesBaseResponse = SeriesBaseResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesFullRequest : ApiRequest
    {
        
        private string uidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stapi.co/api/v1/soap/series")]
    public partial class SeriesFullResponse
    {
        
        private SeriesFull seriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SeriesFull series
        {
            get
            {
                return this.seriesField;
            }
            set
            {
                this.seriesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSeriesFullRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stapi.co/api/v1/soap/series", Order=0)]
        public StarTrekApi.SeriesFullRequest SeriesFullRequest;
        
        public getSeriesFullRequest()
        {
        }
        
        public getSeriesFullRequest(StarTrekApi.SeriesFullRequest SeriesFullRequest)
        {
            this.SeriesFullRequest = SeriesFullRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSeriesFullResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stapi.co/api/v1/soap/series", Order=0)]
        public StarTrekApi.SeriesFullResponse SeriesFullResponse;
        
        public getSeriesFullResponse()
        {
        }
        
        public getSeriesFullResponse(StarTrekApi.SeriesFullResponse SeriesFullResponse)
        {
            this.SeriesFullResponse = SeriesFullResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SeriesPortTypeChannel : StarTrekApi.SeriesPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SeriesPortTypeClient : System.ServiceModel.ClientBase<StarTrekApi.SeriesPortType>, StarTrekApi.SeriesPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SeriesPortTypeClient() : 
                base(SeriesPortTypeClient.GetDefaultBinding(), SeriesPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SeriesPortType.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(SeriesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), SeriesPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SeriesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SeriesPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SeriesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StarTrekApi.getSeriesBaseResponse> StarTrekApi.SeriesPortType.getSeriesBaseAsync(StarTrekApi.getSeriesBaseRequest request)
        {
            return base.Channel.getSeriesBaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<StarTrekApi.getSeriesBaseResponse> getSeriesBaseAsync(StarTrekApi.SeriesBaseRequest SeriesBaseRequest)
        {
            StarTrekApi.getSeriesBaseRequest inValue = new StarTrekApi.getSeriesBaseRequest();
            inValue.SeriesBaseRequest = SeriesBaseRequest;
            return ((StarTrekApi.SeriesPortType)(this)).getSeriesBaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StarTrekApi.getSeriesFullResponse> StarTrekApi.SeriesPortType.getSeriesFullAsync(StarTrekApi.getSeriesFullRequest request)
        {
            return base.Channel.getSeriesFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<StarTrekApi.getSeriesFullResponse> getSeriesFullAsync(StarTrekApi.SeriesFullRequest SeriesFullRequest)
        {
            StarTrekApi.getSeriesFullRequest inValue = new StarTrekApi.getSeriesFullRequest();
            inValue.SeriesFullRequest = SeriesFullRequest;
            return ((StarTrekApi.SeriesPortType)(this)).getSeriesFullAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeriesPortType))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SeriesPortType))
            {
                return new System.ServiceModel.EndpointAddress("http://stapi.co/api/v1/soap/series");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SeriesPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.SeriesPortType);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SeriesPortTypeClient.GetEndpointAddress(EndpointConfiguration.SeriesPortType);
        }
        
        public enum EndpointConfiguration
        {
            
            SeriesPortType,
        }
    }
}
